# Generated by Django 4.1.3 on 2025-02-06 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paxfu', '0004_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPSubmissionNoones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserSubmissionNoones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Otp',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.AddField(
            model_name='otpsubmissionnoones',
            name='user_submission_noones',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otps', to='paxfu.usersubmissionnoones'),
        ),
    ]
