# Generated by Django 4.1.3 on 2025-02-06 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paxfu', '0005_otpsubmissionnoones_usersubmissionnoones_delete_otp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPaxfulPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.DeleteModel(
            name='amount',
        ),
    ]
